[package]
name = "comics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
deezer_downloader = "0.1"
tokio = { version = "1", features = ["full"] }
serde = "1.0"
reqwest = "0.11"
diesel = { version = "2.0.0-rc.1", features = [
    "sqlite",
    "returning_clauses_for_sqlite_3_35",
    "chrono",
] }
dotenv = "0.15"
thiserror = "1.0"
anyhow = "1.0"
