[package]
	edition = "2021"
	name = "comics_rust"
	version = "0.1.0"

[dependencies]
	anyhow = "1"
	# chrono = "0.4"
	clap = { version = "4", features = ["derive", "cargo"] }
	# diesel = { version = "2", features = ["chrono"] }
	# dotenv = "0.15"
	# regex = "1"
	# reqwest = { version = "0.11", features = ["json"] }
	# serde = { version = "1.0", features = ["derive"] }
	# tokio = { version = "1", features = ["full"] }
	walkdir = "2"
	zip = "0.6"
